apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapUsers: | 
    - userarn: arn:aws:iam::646382203106:user/swapnil-globant
      username: swapnil-globant
      groups:
        - system:masters
