---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: employee-mgmt-deployment
 labels:
  type: demo
  author: Swapnil
spec:
 replicas: 2
 selector:
  matchLabels:
   type: demo
   author: Swapnil
 template:
  metadata:
   name: emp-mgmt-app-pod
   labels:
    type: demo
    author: Swapnil
  spec:
   imagePullSecrets:
    - name: ecr-registry-key
   containers:
    - name: emp-mgmt-app
      image: 646382203106.dkr.ecr.ap-south-1.amazonaws.com/demo-registry:latest
      imagePullPolicy: Always
      ports:
       - containerPort: 8080
       ...
