# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: employee-mgmt-system

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Where to deploy (development/staging)?'
        default: 'staging'
        required: true
jobs:
  App-Build:
    if: github.event.inputs.environment == 'development'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.build.outputs.version }}
    steps:
      - name: set variables
        id: build
        run: echo "version=sample" >> "$GITHUB_OUTPUT"
        
  Dev-Deploy:
    if: github.event.inputs.environment == 'development'
    needs: App-Build
    runs-on: ubuntu-latest
    steps:
    - env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      run: |
        echo "Application is deployed into development environment"
  Staging-Deploy:
    if: github.event.inputs.environment == 'staging'
    environment: staging
    runs-on: ubuntu-latest
    steps:
    - env:
        VERSION: ${{ needs.App-Build.outputs.version }}
      run: |
        echo "Deployed in: ${{ github.event.inputs.environment }}"
        echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
        echo "$VERSION"
    
