# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Aew Game Backend Automatic

on:
  workflow_dispatch:

jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "All unit test are executed successfully"
      
  App-Build:
    runs-on: ubuntu-latest
    needs: Unit-Test
    steps:
      - run: echo "Application build successfully"
      
  Docker-Build:
    runs-on: ubuntu-latest
    needs: App-Build
    steps:
      - run: echo "Application build successfully using Dockerfile" 
      
  Development:
    if: github.ref != 'refs/heads/qa'
    runs-on: ubuntu-latest
    needs: Docker-Build
    steps:
    - name: deploying application to develop 
      run: echo "Application is deployed into development environment"
      
  QA:
    if: github.ref == 'refs/heads/qa'
    needs: Docker-Build
    environment: qa
    runs-on: ubuntu-latest
    steps:
    - name: Setting up environment variables
      run: echo "Deployed into Staging"
        
  Staging:
    environment: staging
    runs-on: ubuntu-latest
    steps:
    - name: Setting up environment variables
      run: echo "Deployed into Staging"
      
  Production:
    needs: Staging
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: Setting up environment variables
      run: echo "Deployed into Staging"
    
