# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Aew Game Backend

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Where to deploy (development/staging)?'
        default: 'development'
        required: true
jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'development'
    steps:
      - run: echo "All unit test are executed successfully"
      
  App-Build:
    runs-on: ubuntu-latest
    needs: Unit-Test
    if: github.event.inputs.environment == 'development'
    steps:
      - run: echo "Application build successfully"
      
  Docker-Build:
    runs-on: ubuntu-latest
    needs: App-Build
    if: github.event.inputs.environment == 'development'
    steps:
      - run: echo "Application build successfully using Dockerfile" 
      
  Dev-Deploy:
    runs-on: ubuntu-latest
    needs: Docker-Build
    if: github.event.inputs.environment == 'development'
    outputs:
      version: ${{ steps.step1.outputs.version }}
    steps:
    - id: step1 
      run: |
        echo "version='1.0.0'" >> $GITHUB_OUTPUT
        echo "Application is deployed into development environment"
        
  Staging-Deploy:
    #needs: Dev-Deploy
    if: github.event.inputs.environment == 'staging'
    environment: staging
    runs-on: ubuntu-latest
    steps:
    - name: Setting up environment variables
      run: |
        echo "Deployed in: ${{ github.event.inputs.environment }}"
        echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
        echo ${{ needs.Dev-Deploy.outputs.version }}
    
