# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deployment

on:
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        description: 'IMAGE_TAG'
        required: true
      environment:
        description: 'Where to deploy (staging/production)?'
        default: 'staging'
        required: true

jobs:
  staging:
    if: github.event.inputs.environment == 'staging'
    environment: staging
    runs-on: ubuntu-latest
    steps:
    - env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    - run: |
        echo "${{ github.event.inputs.IMAGE_TAG }}"
        echo "${{ github.event.inputs.environment }}"
        echo "${{ AWS_ACCESS_KEY_ID }}"
  production:
    if: github.event.inputs.environment == 'production'
    environment: production
    runs-on: ubuntu-latest
    needs: staging
    steps:
    - run: |
        echo "${{ github.event.inputs.IMAGE_TAG }}"
        echo "${{ github.event.inputs.environment }}"
        echo "${{ secrets.AWS_ACCESS_KEY_ID }}"
    
